### ISSUE TITLE
Update HRSC links in documentation

### ISSUE THREAD

**Issue by swalterfub** [NASA-AMMOS/AFIDS-POMM#1]
Beginning from section 4.2.1 in the POMM_AFIDS_User_Guide_v1.pdf document, there are several links mentioned pointing to [http://i-mars.eu/web-gis/](http://i-mars.eu/web-gis/). I suggest changing these to the direct links [https://maps.planet.fu-berlin.de](https://maps.planet.fu-berlin.de) as the i-mars links are just i-framed versions of the direct links, with a reduced window size.

**Comment by mikesmyth** [comment]
Links updated.
